<?php

namespace Modules\Shopee\Services;

class Shopee
{
    const WEBHOOK_ORDER_STATUS_UPDATE = 3;
    const WEBHOOK_TRACKING_NO = 4;

    const ORDER_STATUS_UNPAID = 'UNPAID'; // Chờ xác nhận
    const ORDER_STATUS_READY_TO_SHIP = 'READY_TO_SHIP'; // Chờ lấy hàng
    const ORDER_STATUS_RETRY_SHIP = 'RETRY_SHIP';
    const ORDER_STATUS_SHIPPED = 'SHIPPED'; // Đã lấy hàng
    const ORDER_STATUS_TO_CONFIRM_RECEIVE = 'TO_CONFIRM_RECEIVE';
    const ORDER_STATUS_IN_CANCEL = 'IN_CANCEL'; // Đơn huỷ
    const ORDER_STATUS_CANCELLED = 'CANCELLED'; // Đơn huỷ
    const ORDER_STATUS_TO_RETURN = 'TO_RETURN'; // Trả hàng
    const ORDER_STATUS_COMPLETED = 'COMPLETED'; // Đã giao
    const ORDER_STATUS_INVOICE_PENDING = 'INVOICE_PENDING';

    const LOGISTICS_NOT_START = 'LOGISTICS_NOT_START';
    const LOGISTICS_REQUEST_CREATED = 'LOGISTICS_REQUEST_CREATED';
    const LOGISTICS_PICKUP_DONE = 'LOGISTICS_PICKUP_DONE';
    const LOGISTICS_PICKUP_RETRY = 'LOGISTICS_PICKUP_RETRY';
    const LOGISTICS_PICKUP_FAILED = 'LOGISTICS_PICKUP_FAILED';
    const LOGISTICS_DELIVERY_DONE = 'LOGISTICS_DELIVERY_DONE';
    const LOGISTICS_DELIVERY_FAILED = 'LOGISTICS_DELIVERY_FAILED';
    const LOGISTICS_REQUEST_CANCELED = 'LOGISTICS_REQUEST_CANCELED';
    const LOGISTICS_COD_REJECTED = 'LOGISTICS_COD_REJECTED';
    const LOGISTICS_READY = 'LOGISTICS_READY';
    const LOGISTICS_INVALID = 'LOGISTICS_INVALID';
    const LOGISTICS_LOST = 'LOGISTICS_LOST';
    const LOGISTICS_UNKNOWN = 'LOGISTICS_UNKNOWN';

    const ERROR_ACCESS_TOKEN_INVALID = 'ACCESS_TOKEN_INVALID';
    const ERROR_REFRESH_TOKEN_INVALID = 'REFRESH_TOKEN_INVALID';
    const ERROR_NO_LINKED = 'NO_LINKED';
}
