<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro/Ace Laravel Export (1.8.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateDocumentOrderInventoriesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('document_order_inventories', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('document_id')->default(0);
            $table->unsignedInteger('document_exporting_id')->default(0)->index();
            $table->unsignedInteger('order_exporting_id')->default(0)->comment('= 0 nếu không xác nhận được');
            $table->string('barcode', 255)->nullable();
            $table->boolean('checked')->nullable()->default(false)->comment('Đã xác nhận đối soát chưa?');
            $table->nullableTimestamps();
            $table->unique(['document_id', 'order_exporting_id', 'barcode'], 'document_id');

            $table->charset   = 'utf8';
            $table->collation = 'utf8_general_ci';
        });

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('document_order_inventories');
    }
}
