<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro/Ace Laravel Export (1.8.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateOrderPackingsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create("order_packings", function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('shipping_partner_id')->default(0);
            $table->unsignedInteger('tenant_id')->default(0);
            $table->unsignedInteger('merchant_id')->default(0);
            $table->unsignedInteger('order_id')->default(0);
            $table->unsignedInteger('warehouse_id')->default(0);
            $table->unsignedInteger('total_quantity')->default(0);
            $table->unsignedInteger('total_quantity_packaged')->default(0);
            $table->double('total_values', 18, 6)->unsigned()->default(0.000000);
            $table->string('receiver_name')->nullable();
            $table->string('receiver_phone')->nullable();
            $table->string('payment_type')->nullable();
            $table->string('payment_method')->nullable();
            $table->string('status')->default('new')->nullable();
            $table->timestamp('intended_delivery_at')->nullable();
            $table->nullableTimestamps();

            $table->charset   = 'utf8';
            $table->collation = 'utf8_general_ci';
        });

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('order_packings');
    }
}
