<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro/Ace Laravel Export (1.8.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreatePurchasingAccountsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('purchasing_accounts', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('tenant_id')->default(0)->index();
            $table->unsignedInteger('merchant_id')->default(0);
            $table->unsignedInteger('purchasing_service_id')->default(0);
            $table->string('username', 255)->nullable();
            $table->string('password', 255)->nullable();
            $table->string('pin_code', 255)->nullable();
            $table->text('token')->nullable();
            $table->string('status', 255)->nullable()->comment('active|deactive|failed');
            $table->unsignedInteger('creator_id')->default(0);
            $table->timestamp('refresh_token_at')->nullable()->comment('thời điểm gần nhất refresh token');
            $table->nullableTimestamps();
            $table->unique(['username', 'purchasing_service_id', 'tenant_id'], 'merchant_id_2');
            $table->index('merchant_id', 'merchant_id');
            $table->index('purchasing_service_id', 'purchasing_service_id');
            $table->index('status', 'status');
            $table->index('creator_id', 'creator_id');
            $table->softDeletes();

            $table->charset = 'utf8';
            $table->collation = 'utf8_general_ci';
        });

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('purchasing_accounts');
    }
}