<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro/Ace Laravel Export (1.8.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateServiceCombosTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('service_combos', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('service_pack_id')->nullable()->default(0);
            $table->unsignedInteger('tenant_id')->nullable()->default(0);
            $table->unsignedInteger('country_id')->nullable()->default(0);
            $table->string('code', 255)->nullable();
            $table->string('name', 255)->nullable();
            $table->string('note', 255)->nullable();
            $table->unsignedInteger('using_days')->nullable()->default(30)->comment('Ngày sử dụng combo, mặc định 30 ngày');
            $table->unsignedInteger('using_skus')->nullable()->comment('Số lượng sku được dùng trong combo');
            $table->double('suggest_price', 15, 2)->unsigned()->nullable()->default(0.00)->comment('Giá combo đề suất');
            $table->nullableTimestamps();
            $table->unique(['service_pack_id', 'code'], 'service_pack_id');
            $table->index(['tenant_id', 'country_id'], 'tenant_id');
            $table->index('using_days', 'using_days');
            $table->index('using_skus', 'using_skus');
            
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_general_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('service_combos');
    }
}
