<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro/Ace Laravel Export (1.8.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateSkuServicePricesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('sku_service_prices', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('tenant_id')->nullable()->default(0);
            $table->unsignedInteger('product_id')->nullable()->default(0)->comment('Mã dịch vụ');
            $table->unsignedInteger('sku_id')->nullable()->default(0);
            $table->unsignedInteger('service_price_id')->nullable()->default(0);
            $table->unsignedInteger('service_id')->nullable()->default(0);
            $table->nullableTimestamps();
            $table->unique(['sku_id', 'service_price_id', 'service_id'], 'sku_id_2');
            $table->index('product_id', 'product_services_product_id_index');
            $table->index('tenant_id', 'product_service_prices_tenant_id_index');
            $table->index('service_id', 'product_service_prices_service_id_index');
            $table->index('service_price_id', 'product_service_prices_service_price_id_index');
            $table->index('sku_id', 'sku_id');
            
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('sku_service_prices');
    }
}
