<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro/Ace Laravel Export (1.8.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateActiveCodesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('active_codes', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('tenant_id')->nullable()->default(0);
            $table->string('code', 255)->nullable()->comment('Mã kích hoạt');
            $table->string('type', 255)->nullable()->default('service_combo')->comment('Loại mã kích hoạt');
            $table->string('status', 255)->nullable()->default('new')->comment('Trạng thái sử dụng của mã (new,used)');
            $table->timestamp('expired_at')->nullable()->comment('Ngày hết hạn mã');
            $table->nullableTimestamps();
            $table->unique(['tenant_id', 'code', 'type'], 'tenant_id');
            $table->index('status', 'status');
            $table->index('expired_at', 'expired_at');

            $table->charset   = 'utf8mb4';
            $table->collation = 'utf8mb4_general_ci';
        });

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('active_codes');
    }
}
