<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro/Ace Laravel Export (1.8.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreatePickingSessionsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('picking_sessions', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('tenant_id')->nullable()->default(0);
            $table->unsignedInteger('warehouse_id')->nullable()->default(0);
            $table->unsignedInteger('warehouse_area_id')->nullable()->default(0)->comment('vị trí di động, thiết bị thực hiện nhặt hàng');
            $table->unsignedInteger('picker_id')->nullable()->default(0)->comment('nhân viên thực hiện phiên nhặt hàng');
            $table->unsignedInteger('order_quantity')->nullable()->default(0)->comment('Số lượng đơn nhặt ban đầu');
            $table->unsignedInteger('order_packed_quantity')->nullable()->default(0)->comment('Số lượng đơn nhặt hoàn thành trong phiên');
            $table->boolean('is_picked')->nullable()->default(false)->comment('Phiên đã kết thúc nhặt hàng chưa');
            $table->nullableTimestamps();
            $table->index('warehouse_id', 'warehouse_id');
            $table->index('warehouse_area_id', 'warehouse_area_id');
            $table->index('picker_id', 'picker_id');

            $table->charset   = 'utf8';
            $table->collation = 'utf8_general_ci';
        });

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('picking_sessions');
    }
}
