<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro/Ace Laravel Export (1.8.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateDocumentDeliveryComparisonsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('document_delivery_comparisons', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('document_id')->nullable()->default(0);
            $table->unsignedInteger('freight_bill_id')->nullable()->default(0);
            $table->unsignedInteger('order_id')->nullable()->default(0);
            $table->string('freight_bill_code', 255)->nullable();
            $table->unsignedInteger('skus_count_order')->nullable()->default(0)->comment('Tổng sp theo đơn');
            $table->unsignedInteger('skus_count_carrier')->nullable()->default(0)->comment('Tổng sp theo dvvc');
            $table->double('cod_total_order', 16, 2)->unsigned()->nullable()->default(0.00)->comment('Tổng cod theo đơn');
            $table->double('cod_total_carrier', 16, 2)->unsigned()->nullable()->default(0.00)->comment('Tổng cod theo dvvc');
            $table->double('weight_total_order', 10, 2)->unsigned()->nullable()->default(0.00)->comment('Tổng cân nặng theo đơn');
            $table->double('weight_total_carrier', 10, 2)->unsigned()->nullable()->default(0.00)->comment('Tổng cân nặng theo dvvc');
            $table->json('errors')->nullable()->comment('Thông tin lỗi');
            $table->string('status', 100)->nullable()->default('correct');
            $table->nullableTimestamps();
            $table->unique(['document_id', 'freight_bill_code'], 'document_id');
            $table->index('status', 'status');
            
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_general_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('document_delivery_comparisons');
    }
}
