<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro/Ace Laravel Export (1.8.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateLocationShippingPartnersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('location_shipping_partners', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('shipping_partner_id')->index();
            $table->unsignedInteger('location_id')->index();

            $table->unique(['shipping_partner_id', 'location_id'], 'shipping_partner_location');
            $table->timestamps();
        });

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('location_shipping_partners');
    }
}
