<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro/Ace Laravel Export (1.8.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateExpectedTransportingOrderSnapshotsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('expected_transporting_order_snapshots', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('order_id')->nullable();
            $table->double('weight', 12, 3)->unsigned()->nullable()->default(0.000)->comment('cân nặng tính phí');
            $table->json('skus')->nullable()->comment('snapshots skus');
            $table->json('apply_price')->nullable()->comment('snapshots bảng phí áp dụng');
            $table->nullableTimestamps();
            $table->unique('order_id', 'order_id');

            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_general_ci';
        });

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('expected_transporting_order_snapshots');
    }
}
