<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro/Ace Laravel Export (1.8.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateMerchantTransactionsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('merchant_transactions', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('merchant_id')->nullable();
            $table->string('type', 255)->nullable()->comment('type of transaction');
            $table->string('object_type', 255)->nullable();
            $table->unsignedInteger('object_id')->nullable();
            $table->double('amount', 20, 3)->nullable();
            $table->json('metadata')->nullable();
            $table->string('trans_id', 255)->nullable();
            $table->string('m4_trans_id', 255)->nullable();
            $table->nullableTimestamps();
            $table->unique(['type', 'object_type', 'object_id'], 'type');
            $table->unique('trans_id', 'trans_id');
            $table->unique('m4_trans_id', 'm4_trans_id');
            $table->index('merchant_id', 'merchant_id');
            $table->index(['object_type','object_id'], 'object_type');

            $table->charset = 'utf8';
            $table->collation = 'utf8_general_ci';
        });

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('merchant_transactions');
    }
}
