<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro/Ace Laravel Export (1.8.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateExpectedTransportingPriceByWeightsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('expected_transporting_price_by_weights', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('tenant_id')->nullable()->default(0);
            $table->unsignedInteger('warehouse_id')->nullable()->default(0)->comment('áp dụng cho kho');
            $table->unsignedInteger('shipping_partner_id')->nullable()->default(0);
            $table->double('max_weight', 12, 3)->unsigned()->nullable();
            $table->double('unit_price', 12, 3)->unsigned()->nullable();
            $table->double('price', 18, 3)->unsigned()->nullable();
            $table->double('return_price_ratio', 5, 2)->unsigned()->nullable()->default(0.00)->comment('tỷ lệ phí hoàn: 0.1 là 10%');
            $table->unsignedInteger('receiver_ward_id')->nullable()->default(0);
            $table->unsignedInteger('receiver_district_id')->nullable()->default(0);
            $table->unsignedInteger('receiver_province_id')->nullable()->default(0);
            $table->string('receiver_ward', 255)->nullable();
            $table->string('receiver_district', 255)->nullable();
            $table->string('receiver_province', 255)->nullable();
            $table->nullableTimestamps();
            $table->unique(['warehouse_id', 'shipping_partner_id', 'max_weight', 'receiver_ward_id', 'receiver_district_id', 'receiver_province_id'], 'warehouse_id_2');
            $table->index('warehouse_id', 'warehouse_id');
            $table->index('shipping_partner_id', 'shipping_partner_id');
            $table->index('max_weight', 'max_weight');
            $table->index('unit_price', 'unit_price');
            $table->index('price', 'price');
            $table->index('return_price_ratio', 'return_price_ratio');
            $table->index('receiver_ward_id', 'receiver_ward_id');
            $table->index('receiver_district_id', 'receiver_district_id');
            $table->index('receiver_province_id', 'receiver_province_id');
            $table->index(['tenant_id', 'warehouse_id', 'shipping_partner_id'], 'tenant_id');

            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_general_ci';
        });

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('expected_transporting_price_by_weights');
    }
}
