name: Remove artifacts
on:
  workflow_dispatch:
    inputs:
      age:
        description: 'Max artifact age'
        required: true
        default: '1 minutes'
jobs:
  remove:
    runs-on: ubuntu-latest
    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: ${{ github.event.inputs.age }}
